spring:
  application:
    name: auth-service

  config:
    import: "optional:configserver:http://localhost:8888"

jwt:
  secret: "change-this-to-a-long-random-secret-key-for-development-only"
  expiration: 86400000